# Generated by Django 4.0.5 on 2022-08-25 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('intro', models.CharField(max_length=200, verbose_name='説明')),
                ('body', models.TextField(verbose_name='本文')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('upgrade_date', models.DateField(auto_now=True, verbose_name='更新日')),
                ('public', models.BooleanField(default=False, help_text='公開するにはチェックを入れて下さい', verbose_name='公開する')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='カテゴリー')),
            ],
        ),
    ]
